import mongoose from 'mongoose';

const rutinaSchema = new mongoose.Schema(
    {
        // Laboratorio
        Laboratorio:{type:String},
        NumComp:{type:String},
        NumMonitor:{type:String},
        Proyector:{type:String},
        Switch:{type:String},

        CompS1:{type:String},
        CompFecha1:{type:String},
        estatus1:{type:String},
        CompS2:{type:String},
        CompFecha2:{type:String},
        estatus2:{type:String},
        CompS3:{type:String},
        CompFecha3:{type:String},
        estatus3:{type:String},
        CompS4:{type:String},
        CompFecha4:{type:String},
        estatus4:{type:String},
        CompS5:{type:String},
        CompFecha5:{type:String},
        estatus5:{type:String},
        CompS6:{type:String},
        CompFecha6:{type:String},
        estatus6:{type:String},
        CompS7:{type:String},
        CompFecha7:{type:String},
        estatus7:{type:String},
        CompS8:{type:String},
        CompFecha8:{type:String},
        estatus8:{type:String},
        CompS9:{type:String},
        CompFecha9:{type:String},
        estatus9:{type:String},

        //laboratorio 10-19
        CompS10:{type:String},
        CompFecha10:{type:String},
        estatus10:{type:String},
        CompS11:{type:String},
        CompFecha11:{type:String},
        estatus11:{type:String},
        CompS12:{type:String},
        CompFecha12:{type:String},
        estatus12:{type:String},
        CompS13:{type:String},
        CompFecha13:{type:String},
        estatus13:{type:String},
        CompS14:{type:String},
        CompFecha14:{type:String},
        estatus14:{type:String},
        CompS15:{type:String},
        CompFecha15:{type:String},
        estatus15:{type:String},
        CompS16:{type:String},
        CompFecha16:{type:String},
        estatus16:{type:String},
        CompS17:{type:String},
        CompFecha17:{type:String},
        estatus17:{type:String},
        CompS18:{type:String},
        CompFecha18:{type:String},
        estatus18:{type:String},
        CompS19:{type:String},
        CompFecha19:{type:String},
        estatus19:{type:String},
        //laboratorio 20-29
        CompS20:{type:String},
        CompFecha20:{type:String},
        estatus20:{type:String},
        CompS21:{type:String},
        CompFecha21:{type:String},
        estatus21:{type:String},
        CompS22:{type:String},
        CompFecha22:{type:String},
        estatus22:{type:String},
        CompS23:{type:String},
        CompFecha23:{type:String},
        estatus23:{type:String},
        CompS24:{type:String},
        CompFecha24:{type:String},
        estatus24:{type:String},
        CompS25:{type:String},
        CompFecha25:{type:String},
        estatus25:{type:String},
        CompS26:{type:String},
        CompFecha26:{type:String},
        estatus26:{type:String},
        CompS27:{type:String},
        CompFecha27:{type:String},
        estatus27:{type:String},
        CompS28:{type:String},
        CompFecha28:{type:String},
        estatus28:{type:String},
        CompS29:{type:String},
        CompFecha29:{type:String},
        estatus29:{type:String},
        //laboratorio 30-35
        CompS30:{type:String},
        CompFecha30:{type:String},
        estatus30:{type:String},
        CompS31:{type:String},
        CompFecha31:{type:String},
        estatus31:{type:String},
        CompS32:{type:String},
        CompFecha32:{type:String},
        estatus32:{type:String},
        CompS33:{type:String},
        CompFecha33:{type:String},
        estatus33:{type:String},
        CompS34:{type:String},
        CompFecha34:{type:String},
        estatus34:{type:String},
        CompS35:{type:String},
        CompFecha35:{type:String},
        estatus35:{type:String},


        correo: {
            type: String,
            required: true,
        },
    }, {
        timestamps: true
    });

const Rutina = mongoose.model('Rutina', rutinaSchema);
export default Rutina;
